version: 2

sources:
  - name: results
    database: test
    schema: dbt_fal
    tables:
      - name: john_source

models:
  - name: transform
    config:
      materialized: table
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/load_data.py

  - name: dataset
    description: Agent wait time series
    config:
      materialized: table
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/clustering.py
