# This workflow will update the latest version and upload a Python Package using Artifactory on changes to main

name: Upload Python Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # HACK: to avoid error
      # Remove when https://github.com/remorses/bump-version/pull/16 is merged
      - run: git config pull.rebase false

      - name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TOML version
        run: |
          CLIENT_VERSION=$(cat VERSION)
          sed -i "s/999999/$CLIENT_VERSION/g" pyproject.toml

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.4'

      - name: Build and publish
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          JFROG_REPO_URL: ${{ secrets.JFROG_REPO_URL }}
        run: |
            poetry config repositories.artifactory $JFROG_REPO_URL
            poetry publish --build -r artifactory -u $JFROG_USERNAME -p $JFROG_PASSWORD -v -n
